### ISSUE TITLE
天气系列的DEMO是原创吗？

### ISSUE THREAD

**Issue by anhulife** [chokcoco/magicCss#3]
我感觉在`CodePen`上看到过类似的示例。

**Comment by chokcoco** [comment]
@anhulife 
idea 不是原创的，网上貌似有很多CSS实现天气图标的。我是照着样子自己实现了一次，不过有几个是我原创的。

**Comment by chokcoco** [comment]
@anhulife 我看看能不能找到原链接，单标签实现原出处应该也不是在 codePen ，不过 codePen 真是个好地方，经常去逛逛激发灵感。

**Comment by anhulife** [comment]
[Pure CSS One Div Weather Animated Icons](http://codepen.io/fbrz/details/iqtlk/)
